spring:
  config:
    url: "optional:configserver:http://localhost:8080"
  data:
    mongodb:
      host: localhost
      database: avatar
      port: 27017
  application:
    name: avatar

server:
  port: 9010

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka