spring:
  data:
    mongodb:
      host: localhost
      database: avatar
      port: 27017
  application:
    name: Avatar

server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka